# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групы',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_chart.Region', verbose_name='Регион'),
        ),
    ]
