# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_chart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='value',
            new_name='index',
        ),
    ]
